project:
  type: website

website:
  title: "Shashvat Patel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Work Experience
      - href: Projects.qmd
        text: Projects & Papers
  
  page-footer:
    right: "&copy; 2024, Shashvat Patel"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

