---
title: "Work Experience"
---

# Cisco Inc.

In my role, I was responsible for producing comprehensive documentation on Cisco's Security Products, where I utilized my expertise in R and Python to develop data-driven dashboards that offer insightful analytics. My collaboration with the Buying Programs and Security Product Teams was instrumental in identifying a significant revenue gap of \$15 million, which was attributed to overconsumption. To address this challenge and enhance data accessibility and accuracy, I spearheaded the creation of a central data warehouse. This initiative streamlined the collection and analysis of consumption data across Cisco's buying programs and security products, facilitating more informed decision-making and strategic planning.

#  Panorama Education

In my role, I was deeply involved in managing large-client data and ensuring quality assurance for the Customer Experience (CX) team, while concurrently crafting User Stories for the product team to enhance our software development efforts. My responsibilities also extended to the Survey Operations team, where I conducted user research and testing to establish success metrics for the Panorama product, providing valuable insights that shaped our strategic direction. Additionally, I utilized internal systems such as Salesforce, Asana, and Jira to streamline project workflows, which significantly improved our efficiency, evidenced by a reduction of 2.5 days in our average Service Level Agreement (SLA) time. This multi-faceted approach not only optimized our internal processes but also contributed to a more robust and user-centric product development cycle.

# RippleMatch

In my position, I had the opportunity to work closely with the leaders of RippleMatch's Leadership Team, employing Agile frameworks and Scrum methodologies to drive our projects forward effectively. My role involved leveraging growth strategies that successfully increased customer retention by a factor of 1.4 and expanded our user base by 127 users, demonstrating a significant impact on our market presence. Additionally, I took on the responsibility of assessing various growth and performance metrics, which was pivotal in creating detailed progress reports. These reports were not just reflections of our current state but also instrumental in designing new growth strategies. This analytical approach allowed us to continuously refine our tactics and contribute to the company's evolving success story.\
\
\
\
\
